brew_packages:
  - ansible
  - ansible-lint
  - anyenv
  - awscli
  - bat
  - cask
  - commitizen
  - cloc
  - direnv
  - docker-compose
  - duf
  - eza
  - fd
  - fzf
  - gh
  - ghq
  - gibo
  - git
  - git-crypt
  - git-secrets
  - go
  - golangci-lint
  - highlight
  - jq
  - node
  - nodebrew
  - pinentry-mac
  - plantuml
  - protobuf
  - ripgrep
  - starship
  - tbls
  - telnet
  - terminal-notifier
  - terraform
  - tmux
  - tmux-xpanes
  - translate-shell
  - tree
  - tree-sitter-cli
  - wget
  - yarn
  - zplug
  - zsh
brew_cask_apps:
  - 1password
  - bettertouchtool
  - iterm2
  - karabiner-elements
  - raycast
