# https://github.com/tpope/vim-surround
- name: 'pull vim-surround'
  git:
    repo: https://github.com/tpope/vim-surround.git
    dest: ~/.vim/pack/tpope/start/surround
    version: master
  notify: 'setup vim-surround'