- name: set NSGlobalDomain
  osx_defaults:
    key: '{{ item.key }}'
    type: '{{ item.type }}'
    value: '{{ item.value }}'
  with_items: '{{ global_defaults }}'
  tags:
    - osx
- name: set com.apple defaults
  osx_defaults:
    domain: 'com.apple.{{ item.domain }}'
    key: '{{ item.key }}'
    type: '{{ item.type }}'
    value: '{{ item.value }}'
  with_items:
    - '{{ apple_defaults }}'
  tags:
    - osx