name: CI
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@@34e114876b0b11c390a56381ad16ebd13914f8d5 #v4.3.1
      - name: Lint Ansible Playbook
        uses: ansible/ansible-lint-action@main
        uses: ansible-actions/ansible-lint-action@f32438707106decdb067a067e4f026c0e94e3f16 #v1.1.0
        with:
          targets: ./playbooks/mac.yml
          args: -x 701

